"""re-add admin_menu

Revision ID: 14631983b51d
Revises: ec0be0da7b72
Create Date: 2020-06-05 12:23:48.094133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14631983b51d'
down_revision = 'ec0be0da7b72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('name_zh', sa.String(length=128), nullable=True),
    sa.Column('icon_cls', sa.String(length=128), nullable=True),
    sa.Column('component', sa.String(length=128), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_menu')
    # ### end Alembic commands ###
