"""add tables

Revision ID: 661f15dc18bb
Revises: b95749fbf2cd
Create Date: 2020-06-03 16:39:45.782267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '661f15dc18bb'
down_revision = 'b95749fbf2cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_role_permission')
    op.drop_table('admin_permission')
    op.drop_table('jotter_article')
    op.create_unique_constraint(None, 'admin_menu', ['path'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admin_menu', type_='unique')
    op.create_table('jotter_article',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('article_title', sa.VARCHAR(length=255), server_default=sa.text('(NULL)'), nullable=True),
    sa.Column('article_content_html', sa.TEXT(), nullable=True),
    sa.Column('article_content_md', sa.TEXT(), nullable=True),
    sa.Column('article_abstract', sa.VARCHAR(length=255), server_default=sa.text('(NULL)'), nullable=True),
    sa.Column('article_cover', sa.VARCHAR(length=255), server_default=sa.text('(NULL)'), nullable=True),
    sa.Column('article_date', sa.DATETIME(), server_default=sa.text('(NULL)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_permission',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), server_default=sa.text('(NULL)'), nullable=True),
    sa.Column('desc_', sa.VARCHAR(length=100), server_default=sa.text('(NULL)'), nullable=True),
    sa.Column('url', sa.VARCHAR(length=100), server_default=sa.text('(NULL)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_role_permission',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('rid', sa.INTEGER(), server_default=sa.text('(NULL)'), nullable=True),
    sa.Column('pid', sa.INTEGER(), server_default=sa.text('(NULL)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
