"""re-add article

Revision ID: 705f37fb42e2
Revises: 14631983b51d
Create Date: 2020-06-05 12:48:53.129813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '705f37fb42e2'
down_revision = '14631983b51d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_title', sa.String(length=128), nullable=True),
    sa.Column('article_content_md', sa.Text(), nullable=True),
    sa.Column('article_content_html', sa.Text(), nullable=True),
    sa.Column('article_abstract', sa.String(length=128), nullable=True),
    sa.Column('article_cover', sa.String(length=128), nullable=True),
    sa.Column('article_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    # ### end Alembic commands ###
